# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1acI3_ViNGGZmFm3lBNJo_Q9EEF3lDkL6
"""

import streamlit as st
import pandas as pd
from utils import predict_heart_disease

st.title("Heart Disease Prediction System")

age = st.number_input("Age", 1, 100)
sex = st.selectbox("Sex", [0, 1])
cp = st.number_input("Chest Pain Type", 0, 3)
trestbps = st.number_input("Resting Blood Pressure")
chol = st.number_input("Cholesterol")
fbs = st.selectbox("Fasting Blood Sugar", [0, 1])
restecg = st.number_input("Rest ECG", 0, 2)
thalach = st.number_input("Max Heart Rate")
exang = st.selectbox("Exercise Angina", [0, 1])
oldpeak = st.number_input("Oldpeak")
slope = st.number_input("Slope", 0, 2)
ca = st.number_input("CA", 0, 4)
thal = st.number_input("Thal", 0, 3)

if st.button("Predict"):
    data = pd.DataFrame([[age, sex, cp, trestbps, chol,
                          fbs, restecg, thalach,
                          exang, oldpeak, slope,
                          ca, thal]],
                        columns=['age','sex','cp','trestbps',
                                 'chol','fbs','restecg',
                                 'thalach','exang',
                                 'oldpeak','slope',
                                 'ca','thal'])

    result = predict_heart_disease(data)

    if result == 1:
        st.error("High Risk of Heart Disease")
    else:
        st.success("Low Risk of Heart Disease")