# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O7MY7c9bKCuMGKpk-oJVTtrEYXUkXsCc
"""

import joblib
from pathlib import Path
from sklearn.metrics import accuracy_score, recall_score

MODEL_PATH = Path(__file__).parent / "sample_data" / "model.pkl"

def load_model():
    return joblib.load(MODEL_PATH)

def predict_heart_disease(data):
    model = load_model()
    prediction = model.predict(data)
    accuracy = accuracy_score(y_test, pred)
    recall = recall_score(y_test, pred)

    print("Accuracy:", accuracy)
    print("Recall:", recall)
    return prediction[0]
